### ISSUE TITLE
Update plugin information

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-digital-badge#2]
- [x] Update Plugin URI: `https://easydigitaldownloads.com/downloads/digital-badge/`
- [x] Update Author: `Easy Digital Downloads`
- [x] Update readme.txt contributors: `easydigitaldownloads, cklosows, mordauk`

Check off the list once completed: https://trello.com/c/XWLBRC2o/275-update-authorship-of-edd-plugins

**Comment by cklosowski** [comment]
pushed directly into master. pushing the changes to .org
